# Generated by Django 5.1.4 on 2024-12-30 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('tips', models.JSONField()),
                ('examples', models.JSONField()),
                ('code', models.TextField()),
                ('problems', models.JSONField()),
            ],
        ),
    ]
